### ISSUE TITLE
Add Material for MkDocs to regressions

### ISSUE THREAD

**Issue by squidfunk** [mkdocs/regressions#3]
Given that 75% of all sites are built with [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/), it might be a good idea to add [squidfunk/mkdocs-material](https://github.com/squidfunk/mkdocs-material) to the list of projects to test for regressions. I'm not sure what is tested, but a smoke test, at least, would be great ☺️

**Comment by oprypin** [comment]
Yes there are 27 projects using it that are in the set of sites.

https://github.com/mkdocs/regressions/actions/runs/6921658554/job/18827513377#step:5:13

This repo is not about adding plugins/themes to check, it's about adding sites that use various plugins/themes.

**Comment by squidfunk** [comment]
Thanks, that makes sense!
